debian/regolith-control-center/usr/bin/
debian/regolith-control-center/usr/share/applications/org.regolith.Settings.desktop
debian/regolith-control-center/usr/share/dbus-1/services/org.regolith.Settings.service
debian/regolith-control-center/usr/share/glib-2.0/
debian/regolith-control-center/usr/share/icons/regolith-logo.png
debian/regolith-control-center/usr/share/man/
debian/regolith-control-center/usr/share/metainfo/
debian/regolith-control-center/usr/share/regolith-control-center/
